import type {Metadata} from 'next'
import { Noto_Sans} from 'next/font/google'
import 'app/globals.scss'
import {Footer, Header, Sidebar} from '@/components'
import cls from './page.module.scss'
import {clsx} from 'clsx';

const notoSans = Noto_Sans({
  subsets: ['latin', 'cyrillic'],
  weight: ['300', '400', '500', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
    <body className={clsx(notoSans.className, cls.wrapper)}>
    <Header className={cls.header} />
    <Sidebar className={cls.sidebar} />
    <main className={cls.body}>{children}</main>
    <Footer className={cls.footer} />
    </body>
    </html>
  )
}
