import type { Metadata } from "next"
import { Inter, Noto_Sans } from "next/font/google"
import "app/globals.scss"
import { Footer, Header, Sidebar } from "@/components"

const notoSans = Noto_Sans({
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={notoSans.className}>
        <Header />
        <main>
          <Sidebar />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
